"""Build a locally signed app. Runtime paths are machine-local; no keys are bundled."""
import json
import os
import plistlib
import re
import shutil
import subprocess
from pathlib import Path

HERE=Path(__file__).resolve().parent
ROOT=HERE.parent
APP=HERE/'build/NotchPilot.app'


def signing_identity():
    """Keep a developer identity across rebuilds so TCC need not pin each binary hash."""
    configured=os.environ.get('NOTCHPILOT_SIGNING_IDENTITY')
    saved=ROOT/'.cache/notch-signing-identity'
    if configured:return configured
    identities=subprocess.check_output(['security','find-identity','-v','-p','codesigning'],text=True)
    available=re.findall(r'\b([A-F0-9]{40})\s+"Apple Development:[^"]+"',identities)
    if saved.exists():
        identity=saved.read_text().strip()
        if identity not in available:raise RuntimeError('The saved NotchPilot signing identity is unavailable. Select one explicitly with NOTCHPILOT_SIGNING_IDENTITY; do not silently change the app identity.')
        return identity
    if available:
        saved.parent.mkdir(parents=True,exist_ok=True);saved.write_text(available[0]+'\n')
        return available[0]
    print('No Apple Development identity found: ad-hoc signing requires renewed macOS permissions after code changes.')
    return '-'


def main():
    identity=signing_identity()
    runtime=dict(root=str(ROOT),python=str(ROOT/'.cache/notch-venv/bin/python'),
        worker=str(APP/'Contents/Resources/worker.py'),
        planner=str(APP/'Contents/Resources/planner.py'),qwen=str(ROOT/'.cache/notch-qwen3-1.7b'),
        downloader=str(APP/'Contents/Resources/download_models.py'),
        whisper=str(ROOT/'.cache/whisper.cpp/build/bin/whisper-cli'),
        model=str(ROOT/'.cache/whisper-models/ggml-base.en.bin'))
    for key in ('python','whisper'):
        if not Path(runtime[key]).exists():raise RuntimeError('Missing runtime dependency: '+key)
    macos=APP/'Contents/MacOS';res=APP/'Contents/Resources'
    macos.mkdir(parents=True,exist_ok=True);res.mkdir(parents=True,exist_ok=True)
    # Older builds may have generated bytecode here. Bundled Python now runs with -B.
    shutil.rmtree(res/'__pycache__',ignore_errors=True)
    subprocess.run(['swiftc','-swift-version','5','-parse-as-library','-O',*[str(p) for p in sorted((HERE/'Sources').glob('*.swift'))],
        '-o',str(macos/'NotchPilot'),'-framework','SwiftUI','-framework','AppKit','-framework','AVFoundation',
        '-framework','Carbon','-framework','ApplicationServices','-framework','Security','-framework','ScreenCaptureKit'],check=True)
    shutil.copy2(HERE/'worker.py',res/'worker.py')
    shutil.copy2(HERE/'planner.py',res/'planner.py')
    for filename in ('download_models.py','models.json','navigation.py','flights.py','browser_agent.py','native_browser.py','cua_agent.py','dictation.py'):
        shutil.copy2(HERE/filename,res/filename)
    cua_binary=subprocess.check_output([runtime['python'],'-B','-c','from cua_driver import get_binary_path; print(get_binary_path())'],text=True).strip()
    shutil.copy2(cua_binary,res/'cua-driver')
    subprocess.run(['codesign','--force','--sign',identity,str(res/'cua-driver')],check=True)
    shutil.copy2(HERE/'CUA-LICENSE.txt',res/'cua-LICENSE.txt')
    (res/'runtime.json').write_text(json.dumps(runtime,indent=2)+'\n')
    for name,repo in [('typesafe-computer-use','typesafe-computer-use'),('whisper.cpp','whisper.cpp')]:
        shutil.copy2(ROOT/'.cache'/repo/'LICENSE',res/(name+'-LICENSE.txt'))
    shutil.copy2(ROOT/'.cache/jev-ultrafast/LICENSE',res/'jev-ultrafast-LICENSE.txt')
    info=dict(CFBundleIdentifier='local.notchpilot.app',CFBundleName='NotchPilot',CFBundleDisplayName='NotchPilot',
        CFBundleExecutable='NotchPilot',CFBundlePackageType='APPL',CFBundleShortVersionString='0.3.0',CFBundleVersion='3',
        LSMinimumSystemVersion='14.0',LSUIElement=True,NSHighResolutionCapable=True,
        NSMicrophoneUsageDescription='Transcribe your spoken commands locally with Whisper.',
        NSScreenCaptureUsageDescription='Read the active app to identify controls for your command.')
    (APP/'Contents/Info.plist').write_bytes(plistlib.dumps(info))
    subprocess.run(['codesign','--force','--deep','--sign',identity,str(APP)],check=True)
    versions={repo:subprocess.check_output(['git','-C',str(ROOT/'.cache'/repo),'rev-parse','HEAD'],text=True).strip()
              for repo in ('typesafe-computer-use','whisper.cpp')}
    versions['models']=json.loads((HERE/'models.json').read_text())
    versions['signing']='ad-hoc' if identity=='-' else 'Apple Development'
    (HERE/'build/runtime-versions.json').write_text(json.dumps(versions,indent=2)+'\n')
    print(APP)


if __name__=='__main__':main()
